spring.application.name=findup
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d8urh3urnols73fke8qg-a/findup_banco
spring.datasource.username=Uo100Uatm1GM3RTfRqQGYLQUs94g8WZR
spring.datasource.password=300407

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true